version: '3'
services:
  app:
    build: .
    container_name: nodejs-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydb"
      JWT_SECRET: "your_jwt_secret"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
